---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fragile-deployment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fragile-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: fragile-deployment
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragile
spec:
  selector:
    matchLabels:
      app: fragile
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fragile
      annotations:
        helm-release-revision: "{{ .Release.Revision }}"
    spec:
      serviceAccountName: fragile-deployment
      initContainers:
      - name: helm
        image: lachlanevenson/k8s-kubectl:v1.24.3
        command:
         - sh
         - -cex
         - |
            if kubectl get job fragile; then
              kubectl wait --for=condition=complete job/fragile
            fi 
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1